- name: install cilium helm repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

# TODO this is always reporting as changed :/
- name: install cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: 1.16.3
    release_namespace: kube-system
    set_values:
      - value: ingressController.enabled=true
      - value: ingressController.loadbalancerMode=dedicated
      - value: ingressController.service.type=LoadBalancer
      - value: ingressController.default=true
      - value: kubeProxyReplacement=true
      - value: k8sServicePort=6443
      - value: "k8sServiceHost={{ ansible_default_ipv4.address }}"
      - value: l2announcements.enabled=true
      - value: k8sClientRateLimit.qps=80
      - value: k8sClientRateLimit.burst=160
      - value: externalIPs.enabled=true
      - value: "ipam.operator.clusterPoolIPv4PodCIDRList=10.2.0.0/20"


- name: copy cilium extra config
  copy:
    src: cilium-config.yml
    dest: ~/definitions/cilium/

- name: create cilium extra config
  kubernetes.core.k8s:
    state: present
    apply: true
    src: ~/definitions/cilium/cilium-config.yml
