- name: install longhorn helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: install longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    chart_version: 1.7.2

- name: copy longhorn ingress definition
  copy:
    src: longhorn-ingress.yml
    dest: ~/definitions/longhorn/

- name: create longhorn ingress
  kubernetes.core.k8s:
    state: present
    apply: true
    src: ~/definitions/longhorn/longhorn-ingress.yml
  
