- name: create lubelogger namespace
  tags: lubelogger
  kubernetes.core.k8s:
    name: lube-logger
    api_version: v1
    kind: Namespace
    state: present

- name: copy lube logger template
  tags: lubelogger
  copy:
    src: lubelogger.yml
    dest: ~/definitions/lubelogger/

- name: apply lube logger definition
  tags: lubelogger
  kubernetes.core.k8s:
    apply: true
    state: present
    src: ~/definitions/lubelogger/lubelogger.yml
    namespace: lube-logger

- name: create mealie namespace
  tags: mealie
  kubernetes.core.k8s:
    name: mealie
    api_version: v1
    kind: Namespace
    state: present

- name: copy mealie template
  tags: mealie
  copy:
    src: mealie.yml
    dest: ~/definitions/mealie/

- name: apply mealie definition
  tags: mealie
  kubernetes.core.k8s:
    apply: true
    state: present
    src: ~/definitions/mealie/mealie.yml
    namespace: mealie