- name: create monitoring namespace
  tags: monitoring
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: copy influxdb template
  tags: monitoring
  copy:
    src: influxdb.yml
    dest: ~/definitions/monitoring/

- name: apply influxdb definition
  tags: monitoring
  kubernetes.core.k8s:
    apply: true
    state: present
    src: ~/definitions/monitoring/influxdb.yml
    namespace: monitoring
